server {
  listen 8080;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  # Security Headers
  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Content-Type-Options "nosniff";

  # Angular routing
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Static Assets Caching
  location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|map)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public, immutable";
  }

  # Optioanl: Explicit asset route
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  if ($http_x_forwarded_proto = "http") {
    return 301 https://$host$request_uri;
  }

  gzip on;
  gzip_types text/plain text/css application/json application/javascript;
}
