name: Security Scan for Angular application

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Initialize CodeQL
        uses: github/codeql-action/init@9e0d7b8d25671d64c341c19c0152d693099fb5ba
        with:
          languages: javascript-typescript
      - name: Perform Analysis
        uses: github/codeql-action/analyze@9e0d7b8d25671d64c341c19c0152d693099fb5ba
        with:
          category: "/language:javascript-typescript"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:main
          format: sarif
          output: trivy-scan-results.sarif
          vuln-type: os,library
          severity: CRITICAL,HIGH
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@9e0d7b8d25671d64c341c19c0152d693099fb5ba
        with:
          sarif_file: trivy-scan-results.sarif
          category: trivy-scan
